PrimeFaces.locales['en_GB'] = {
                firstDay : 1,
                closeText: 'Закрыть',
                prevText: 'Назад',
                nextText: 'Вперёд',
                currentText: 'Home',
                monthNames: ['Январь', 'Февраль' , 'Март' , 'Апрель' , 'Май' , 'Июнь' , 'Июль' , 'Август' , 'Сентябрь','Октябрь','Ноябрь','Декабрь' ],
                monthNamesShort: ['Январь', 'Февраль' , 'Март' , 'Апрель' , 'Май' , 'Июнь' , 'Июль' , 'Август' , 'Сентябрь','Октябрь','Ноябрь','Декабрь' ],
                dayNames: ['Воскресенье', 'Понедельник', 'Вторник', 'Среда', 'Четверг', 'Пятница', 'Суббота'],
                dayNamesShort: ['Воск','Пон' , 'Вт' , 'Ср' , 'Четв' , 'Пят' , 'Суб'],
                dayNamesMin: ['Вс', 'Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб'],
                weekHeader: 'Неделя',
                isRTL: false,
                showMonthAfterYear: false,
                yearSuffix:'',
                timeOnlyTitle: 'Только время',
                timeText: 'Время',
                hourText: 'Час',
                minuteText: 'Минута',
                secondText: 'Секунда',
                currentText: 'Сегодня',
                ampm: false,
                month: 'Месяц',
                week: 'Неделя',
                day: 'День',
                allDayText: 'Весь день'
            };